### PR TITLE
add function for counting hosts in a net

### PR DESCRIPTION
**Pull request by jcgruenhage**

### CODE REVIEW

**Comment by krisprice** [comment]
Hi @jcgruenhage, I see `host_count()` doesn't handle IPv4 cases where the prefix length is less than 31 and the subnet and broadcast addresses should be exclused. BTW the host count can be obtained at the moment through `hosts().count()`. Does that work for your case?

**Comment by jcgruenhage** [comment]
> Hi @jcgruenhage, I see `host_count()` doesn't handle IPv4 cases where the prefix length is less than 31

my (doc) test case should cover that, and afaict it works as expected.

> and the subnet and broadcast addresses should be exclused

I've talked about this with the guy that's using this, and I'm not 100% sure on this. This would mean subtracting 2 from the current result, right? This would not work very well for the counting hosts in nested networks where some have a flag set.

Let's assume we have a /8 which has a this flag set, and a /24 in there which doesn't have the flag set, and we want to know the total amount of hosts that have the flag set. Without excluding the subnet and broadcast IPs, this would just be `(2^24)-(2^8)`.
When excluding them, you'd instead calculate `(2^24 - 2) - (2^8 - 2)`, which in this case comes to the same result, but with a very different meaning, because the subnet and broadcast addresses of the inner net are counted, which does not make any sense.

> the host count can be obtained at the moment through `hosts().count()`. Does that work for your case?

I don't know much about compiler optimisation, so not sure whether this would be any slower, but my intuition would say that this at least involves a few copies and more calculations, so would be a slower. I'd be quite interested in benchmarking this, but don't have the time right now. As this code is executed on a fairly long list of CIDRs (iirc a few MB), this could actually make a difference. Currently most time is spent decoding the list, but this will likely change one the list is not a CSV file anymore.

**Comment by krisprice** [comment]
> my (doc) test case should cover that, and afaict it works as expected.

Yep I see that. There was a slight misunderstanding: stress the and in my statement, that is I'm saying when prefix length is <31 then the subnet and broadcast should be excluded.

> I've talked about this with the guy that's using this, and I'm not 100% sure on this. This would mean subtracting 2 from the current result, right? This would not work very well for the counting hosts in nested networks where some have a flag set.

Ah I see. That seems like a different meaning. I wouldn't want to change the meaning of "host" count for that. Maybe there's a different name for a function that is useful to return the number of addresses *inclusive* of the network and broadcast? `size()`? `address_count()`? Something else... Not sure what would be better? I hate naming things.

> I don't know much about compiler optimisation, so not sure whether this would be any slower, but my intuition would say that this at least involves a few copies and more calculations, so would be a slower. I'd be quite interested in benchmarking this, but don't have the time right now. As this code is executed on a fairly long list of CIDRs (iirc a few MB), this could actually make a difference. Currently most time is spent decoding the list, but this will likely change one the list is not a CSV file anymore.

Is it executed that frequently? If not optimizing it here may not be worthwhile, but if optimization is necessary then it may be a good reason for your friend to use his own code for this particular purpose.

**Comment by jcgruenhage** [comment]
> There was a slight misunderstanding: stress the and in my statement, that is I'm saying when prefix length is <31 then the subnet and broadcast should be excluded.

ah, okay yeah, then that makes sense, yeah.

> Ah I see. That seems like a different meaning. I wouldn't want to change the meaning of "host" count for that. Maybe there's a different name for a function that is useful to return the number of addresses _inclusive_ of the network and broadcast? `size()`? `address_count()`? Something else... Not sure what would be better? I hate naming things.

Naming is annoying, yeah. Maybe it'd be worth documenting that the subnet and broadcast addresses are excluded in `hosts()`, because I wouldn't have assumed so myself, even though it does make sense. Maybe `hosts()`, `addresses()`, `host_count()` and `address_count()` should just all be provided?

> Is it executed that frequently? If not optimizing it here may not be worthwhile, but if optimization is necessary then it may be a good reason for your friend to use his own code for this particular purpose.

The whole tool isn't executed that often, but that specific function is called for a few hundred thousand networks each time the tool is executed, so optimizing this step does make sense IMO. He is using his own code right now, which is very similar to what I'm doing here, but I thought getting it upstream would be desirable, as I think he'll not be the only one to run into things like this.

**Comment by h4cnull** [comment]
Maybe 192.168.0.0 or 192.168.0.255 should be contained in "192.168.0.0/24"，crate has provided netwrok(),broadcast() for "suggestion"，also hosts() just provide hosts suggestion。the truly network address or broadcast should be "defined" by user self. 
maybe addresses(), address_count() should just all be provided?

**Pull request closed without merging**
