### PR TITLE
Add no_std support on nightly

### PR DESCRIPTION
**Pull request by domenukk**
This PR adds no_std support using the unstable ip_in_core and error_in_core features.
(Cleaned up version of #49 )

### CODE REVIEW

**Comment by domenukk** [comment]
@krisprice does the PR look good to you like this?

**Comment by krisprice** [comment]
Thanks @domenukk, if I run a `cargo test --all-features` it spits a number of errors, can you run and then resolve those errors?

**Comment by domenukk** [comment]
Good catch, some imports were missing. Fixed :)

**Comment by domenukk** [comment]
Everything good now? Thanks :)

**Comment by krisprice** [comment]
Merged and published. Thanks for the work. :-)

**Pull request merged**
