### PR TITLE
From impls

### PR DESCRIPTION
**Pull request by djc**
Add a number of `From` impls that parallel the std impls:

Screenshot 2024-11-25 at 12 42 45

This avoids the need for relying on `FromStr` impls in constants.

### CODE REVIEW

**Comment by krisprice** [comment]
Thanks @djc - I'm wondering if its a problem that this allows creation of IpNets that have invalid prefix lengths, e.g. `Ipv4Net::from(([1u8, 2u8, 3u8, 4u8], 123))` will work. What do you think?

**Comment by djc** [comment]
Ah, good point. How do you feel about `Ipv4Net::from_array_assert(ip: [u8; 4], u8)` (and similar for IPv6) instead?

**Comment by krisprice** [comment]
I wondered about just clamping the prefix length, the `From<Ipv4Addr>` impl for example just defaults the prefix length to 32, but this is a natural conversion for an IP address that I don't think violates the principals of From. Clamping the given length I think would violate the intention of From. 

Would `TryFrom` make sense here?

Adding a `Ipv4Net::from_array_assert(ip: [u8; 4], u8)` could be done, but since it offers none of the benefits of implementing `From`, maybe this is just easier as a helper function in your project?

**Comment by djc** [comment]
Okay, I guess this PR was not actually what I really wanted because what I'd really like is to make this have less boilerplate:

```rust
const RECOMMENDED_SERVER_FILTERS: [IpNet; 22] = [
    IpNet::new_assert(IpAddr::V4(Ipv4Addr::new(127, 0, 0, 0)), 8), // Loopback range
    IpNet::new_assert(IpAddr::V4(Ipv4Addr::UNSPECIFIED), 8),       // Unspecified range
    IpNet::new_assert(IpAddr::V4(Ipv4Addr::BROADCAST), 32),        // Directed Broadcast
    IpNet::new_assert(IpAddr::V4(Ipv4Addr::new(10, 0, 0, 0)), 8),  // RFC 1918 space
    IpNet::new_assert(IpAddr::V4(Ipv4Addr::new(172, 16, 0, 0)), 12), // RFC 1918 space
    IpNet::new_assert(IpAddr::V4(Ipv4Addr::new(192, 168, 0, 0)), 16), // RFC 1918 space
    IpNet::new_assert(IpAddr::V4(Ipv4Addr::new(100, 64, 0, 0)), 10), // CG NAT
    IpNet::new_assert(IpAddr::V4(Ipv4Addr::new(169, 254, 0, 0)), 16), // Link-local space
    IpNet::new_assert(IpAddr::V4(Ipv4Addr::new(192, 0, 0, 0)), 24), // IETF Reserved
    IpNet::new_assert(IpAddr::V4(Ipv4Addr::new(192, 0, 2, 0)), 24), // TEST-NET-1
    IpNet::new_assert(IpAddr::V4(Ipv4Addr::new(198, 51, 100, 0)), 24), // TEST-NET-2
    IpNet::new_assert(IpAddr::V4(Ipv4Addr::new(203, 0, 113, 0)), 24), // TEST-NET-3
    IpNet::new_assert(IpAddr::V4(Ipv4Addr::new(240, 0, 0, 0)), 4), // Class E Reserved
    IpNet::new_assert(IpAddr::V6(Ipv6Addr::LOCALHOST), 128),       // v6 loopback
    IpNet::new_assert(IpAddr::V6(Ipv6Addr::UNSPECIFIED), 128),     // v6 unspecified
    IpNet::new_assert(IpAddr::V6(Ipv6Addr::new(0x100, 0, 0, 0, 0, 0, 0, 0)), 64), // v6 discard prefix
    IpNet::new_assert(
        IpAddr::V6(Ipv6Addr::new(0x2001, 0xdb8, 0, 0, 0, 0, 0, 0)),
        32,
    ), // v6 documentation prefix
    IpNet::new_assert(IpAddr::V6(Ipv6Addr::new(0x3fff, 0, 0, 0, 0, 0, 0, 0)), 20), // v6 documentation prefix
    IpNet::new_assert(IpAddr::V6(Ipv6Addr::new(0x5f00, 0, 0, 0, 0, 0, 0, 0)), 16), // v6 segment routing prefix
    IpNet::new_assert(IpAddr::V6(Ipv6Addr::new(0xfc00, 0, 0, 0, 0, 0, 0, 0)), 7), // v6 private address,
    IpNet::new_assert(IpAddr::V6(Ipv6Addr::new(0xfe80, 0, 0, 0, 0, 0, 0, 0)), 64), // v6 link local
    IpNet::new_assert(IpAddr::V6(Ipv6Addr::new(0xff00, 0, 0, 0, 0, 0, 0, 0)), 8), // v6 multicast
];
```

(So it has to be `const`, which `From` impls aren't.)

Maybe `IpNet::new_v4_assert(octets: [u8; 4], u8)`?

**Comment by krisprice** [comment]
I see now. I don't think it makes sense to add that just to reduce boiler plate. Maybe a macro would work here to get the result you want and make maintaining the list a little cleaner? E.g.

```
macro_rules! ipnet {
    ($a:expr, $b:expr, $c:expr, $d:expr, $l:expr) => (IpNet::new_assert(IpAddr::V4(Ipv4Addr::new($a, $b, $c, $d)), $l));
    ($a:expr, $b:expr, $c:expr, $d:expr, $e:expr, $f:expr, $g:expr, $h:expr, $l:expr) =>
        (IpNet::new_assert(IpAddr::V6(Ipv6Addr::new($a, $b, $c, $d, $e, $f, $g, $h)), $l));
}

const filter_list: [IpNet; 2] = [
    ipnet!(10, 0, 0, 0, 8),
    ipnet!(0x2001, 0xdb8, 0, 0, 0, 0, 0, 0, 32),
];
```

**Comment by djc** [comment]
Given that std already has `From` impls, IMO it would still make sense to do something similar here. Maybe this crate should include such macros if you don't want to add more `const` functions?

**Pull request closed without merging**
